language: android
jdk: oraclejdk8
cache: false
sudo: false
env:
  global: [ANDROID_API_LEVEL=21, ANDROID_BUILD_TOOLS_VERSION=21.1.2, ANDROID_ABI=armeabi-v7a,
    ADB_INSTALL_TIMEOUT=8]
android:
  components: [platform-tools, tools, build-tools-$ANDROID_BUILD_TOOLS_VERSION, android-$ANDROID_API_LEVEL,
    extra-google-google_play_services, extra-android-support, extra-google-m2repository,
    extra-android-m2repository, sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL]
before_script: [echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL
    --abi $ANDROID_ABI, emulator -avd test -no-skin -no-audio -no-window &]
script: [./wait_for_emulator, ./gradlew connectedCheck -PdisablePreDex]
notifications:
  webhooks:
    urls: ['https://webhooks.gitter.im/e/92762176661b63005621']
    on_success: always
    on_failure: always
    on_start: false
branches:
  only: [CUTR-at-USF/OpenTripPlanner-for-Android-498-GRADLE_DAEMON]
