sudo: false
dist: trusty
language: java
install: true
jdk: [oraclejdk8, openjdk11, openjdk13]
env:
  matrix: [TERM=dumb]
before_install: null
before_script: [./gradlew --version]
script: [TERM=dumb ./gradlew clean build -S]
after_success: [TERM=dumb ./gradlew test jacocoTestReport jacocoRootReport coveralls
    -S]
branches:
  only: [miho/VWorkflows-71-origin]
