language: java
jdk: [openjdk8]
jobs:
  include:
  - {stage: Subproject-expression, install: cd sub_projects/expression, script: ./gradlew
      build publish}
  - {stage: build, install: ./gradlew setupCiWorkspace, script: ./gradlew test}
  - {stage: checkstyle, install: echo "skipping default ./gradlew assemble", script: ./gradlew
      checkstyle}
env: {global: TERM=dumb}
branches:
  only: [BuildCraft/BuildCraft-4659-origin]
