sudo: false
jdk: [oraclejdk8]
language: android
android:
  components: [tools, tools, build-tools-29.0.2, android-29, extra-android-support,
    extra-google-google_play_services, extra-google-m2repository, extra-android-m2repository]
script: ./gradlew clean check assembleDebug
branches:
  only: [serso/android-checkout-179-FILE_SYSTEM_WATCHING]
