git: {depth: 3}
language: java
jdk: [openjdk8]
addons:
  apt: {update: true}
  chrome: stable
cache:
  directories: [$HOME/.gradle/caches/, $HOME/.gradle/wrapper/]
before_install: [sudo apt-get install -y libappindicator1 fonts-liberation, export
    CHROME_BIN=/usr/bin/google-chrome]
install: true
script: java -version; ./gradlew clean test chrome
branches:
  only: [selenide-examples/hangman-7-origin]
