language: android
android:
  components: [tools, platform-tools, tools, build-tools-26.0.2]
  licenses: [android-sdk-license-bcbbd656, .*intel.+]
env:
  matrix: ['ANDROID_SDKS=android-25,sysimg-25  ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a']
before_install: [android list sdk --extended --no-ui --all, echo y | android update
    sdk --no-ui --all --filter sys-img-armeabi-v7a-android-24, echo no | android create
    avd --force -n test -t android-24 --abi $ANDROID_ABI, emulator -avd test -no-skin
    -no-audio -no-window &]
before_script: [chmod a+x ./ci/wait_for_emulator, ./ci/wait_for_emulator, adb shell
    input keyevent 82 &]
branches:
  only: [openintents/shoppinglist-76-PARALLEL_BUILDS]
