language: android
android:
  components: [tools, tools, platform-tools, android-28, build-tools-28.0.3, extra]
  licenses: [android-sdk-license-.+]
jdk: oraclejdk8
notifications: {email: false}
sudo: required
before_install: [yes | sdkmanager "platforms;android-28"]
script: [./gradlew clean build, ./gradlew test]
branches:
  only: [pockethub/PocketHub-1294-origin]
