sudo: false
language: java
jdk: [oraclejdk8, oraclejdk9]
after_success: [./gradlew jacocoTestReport coveralls]
cache:
  directories: [$HOME/.gradle/caches/, $HOME/.gradle/wrapper/]
branches:
  only: [mkarneim/pojobuilder-170-origin]
