language: android
jdk: [oraclejdk8]
addons:
  apt:
    packages: [graphviz]
android:
  components: [tools, android-29, add-on, extra]
before_install: [yes | sdkmanager "platforms;android-23"]
script: [jdk_switcher use oraclejdk8, './gradlew assemble  libK3b:test libK3bZip:test']
branches:
  only: [k3b/ToGoZip-27-PARALLEL_BUILDS]
