sudo: false
dist: trusty
language: java
jdk: [openjdk8]
services: [docker]
script:
- |
  if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
    echo "On Branch $TRAVIS_BRANCH, building Latest images"
    ./gradlew dockerImage
  else
    if [ -n "$TRAVIS_TAG" ]; then
      echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
      echo "On Tag $TRAVIS_TAG, building Latest images"
      ./gradlew dockerImage
    else
      echo "On Branch $TRAVIS_BRANCH, checking build"
      ./gradlew check
    fi
  fi
after_success: ['wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh',
  chmod +x send.sh, ./send.sh success $WEBHOOK_URL]
after_failure: ['wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh',
  chmod +x send.sh, ./send.sh failure $WEBHOOK_URL]
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew dockerImage && bash scripts/deploy_docker_images.sh $TRAVIS_TAG
  true: {tags: true}
branches:
  only: [sitewhere/sitewhere-977-origin]
