sudo: true
language: bash
dist: bionic
stages: [install, unit_test, test, finalize_coverage, cache]
env:
  global: [COMPILE_API=29, ANDROID_BUILD_TOOLS=29.0.2, ABI=x86_64, ADB_INSTALL_TIMEOUT=8,
    'ANDROID_HOME=${HOME}/android-sdk', 'ANDROID_TOOLS_URL="https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip"',
    EMU_FLAVOR=default, 'GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"',
    JDK="1.8", 'TOOLS=${ANDROID_HOME}/tools', 'PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}',
    UNIT_TEST=FALSE, FINALIZE_COVERAGE=FALSE]
  matrix: [API=24, API=25, API=27, API=28, API=29]
before_install: ['curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh',
  'export TARGET_JDK="${JDK}"', JDK="1.8", source ~/.install-jdk-travis.sh, 'if [
    "$FINALIZE_COVERAGE" = "FALSE" ]; then wget -q "${ANDROID_TOOLS_URL}" -O android-sdk-tools.zip;
    fi', 'if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then unzip -q android-sdk-tools.zip
    -d ${ANDROID_HOME}; fi', 'if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then rm android-sdk-tools.zip;
    fi', 'if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then mkdir ~/.android; fi', 'if [
    "$FINALIZE_COVERAGE" = "FALSE" ]; then echo ''count=0'' > ~/.android/repositories.cfg;
    fi', 'if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then yes | sdkmanager --licenses
    >/dev/null; fi', 'if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then echo y | sdkmanager
    --no_https "platform-tools" >/dev/null; fi', 'if [ "$FINALIZE_COVERAGE" = "FALSE"
    ]; then echo y | sdkmanager --no_https "tools" >/dev/null; fi', 'if [ "$FINALIZE_COVERAGE"
    = "FALSE" ]; then echo y | sdkmanager --no_https "build-tools;${ANDROID_BUILD_TOOLS}"
    >/dev/null; fi', 'if [ "$FINALIZE_COVERAGE" = "FALSE" ]; then echo y | sdkmanager
    --no_https "platforms;android-${COMPILE_API}" >/dev/null; fi']
install:
- echo y | sdkmanager --no_https "platforms;android-$API" >/dev/null
- echo y | sdkmanager --no_https "emulator" >/dev/null
- echo y | sdkmanager --no_https "system-images;android-$API;$EMU_FLAVOR;$ABI" >/dev/null
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends install bridge-utils
  libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder
- sudo adduser $USER libvirt
- sudo adduser $USER kvm
- echo no | avdmanager create avd --force -n test -k "system-images;android-$API;$EMU_FLAVOR;$ABI"
  -c 10M
- |
  EMU_PARAMS="-verbose -no-snapshot -no-window -camera-back none -camera-front none -selinux permissive -qemu -m 2048"
  EMU_COMMAND="emulator"
  # This double "sudo" monstrosity is used to have Travis execute the
  # emulator with its new group permissions and help preserve the rule
  # of least privilege.
  sudo -E sudo -u $USER -E bash -c "${ANDROID_HOME}/emulator/${EMU_COMMAND} -avd test ${AUDIO} ${EMU_PARAMS} &"
- chmod +x ./tools/android-wait-for-emulator.sh
- ./tools/android-wait-for-emulator.sh
- adb shell input keyevent 82 &
- JDK="${TARGET_JDK}"
- source ~/.install-jdk-travis.sh
script:
- chmod +x gradlew
- |
  ./gradlew build assembleAndroidTest
  retval=$?
  if [ $retval -ne 0 ]; then
    echo "error on assembling, exit code: "$retval
    exit $retval
  fi
- |
  ./gradlew :app:installDebug :app:installDebugAndroidTest
  retval=$?
  if [ $retval -ne 0 ]; then
    echo "error on install, exit code: "$retval
    exit $retval
  fi
- |
  adb shell am instrument -w -r -e debug false org.andstatus.todoagenda.tests/androidx.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
  retval=$?
  if [ $retval -ne 0 ]; then
    echo "error in adb, exit code: "$retval
    exit $retval
  fi
- |
  cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
  if [ $? -eq 0 ]; then
    echo "Test failure found"
    exit 1
  else
    cat build/adb-test.log | grep "OK ("
  fi
after_success: echo "After success"
before_cache: [rm -f $HOME/.gradle/caches/modules-2/modules-2.lock, 'curl "${GRAVIS}.clean_gradle_cache.sh"
    --output ~/.clean_gradle_cache.sh', bash ~/.clean_gradle_cache.sh > /dev/null]
cache:
  directories: [$HOME/.gradle/caches/, $HOME/.gradle/wrapper/]
notifications: {email: false}
branches:
  only: [plusonelabs/calendar-widget-374-origin]
