sudo: false
language: android
android:
  components: [build-tools-23.0.1, android-23, android-10, extra-android-m2repository,
    sys-img-armeabi-v7a-android-18]
  licenses: [android-sdk-license-.+]
jdk: [oraclejdk8]
env:
  global:
  - {secure: VgzgkHpv8GQtVighZP+Fnkeaj08Abk8c+HJePEkO+0c1aoeL0Lwt6yUwXrMlPhgBndLi9foDZV1PH1xVxLlnj5u5GA8hNoNY4cOxjvEpD3E9MQ0gsdKmclMsoodJpY6YQ67FMexW6IVOHxkHcbEFm7ylcobmhyyX+MHujir980s=}
  - {secure: GdbZFkBJYt7nuAg8VJytyFFwW/HPpH/kcXXtdjH7Dw5dF/rw1QlBkMCrzVPYv1QgaBW6eprdWQ1OeSi8A4puK/jMGyAxcLVjmop1167MUQjt1C9HuY1HjMiwCrTpbdHchPSQd37cg++sbJ9AXaKdfRxLZ/knMKLtcH/p8d8DHWQ=}
  matrix: [ANDROID_TARGET=android-18 ANDROID_ABI=armeabi-v7a]
before_install: [export TERM=dumb]
install: [./gradlew assemble]
script: [./gradlew --continue check]
after_success: [chmod +x scripts/deploy_to_maven.sh, ./scripts/deploy_to_maven.sh]
branches:
  only: [stanfy/enroscar-74-PARALLEL_BUILDS]
