sudo: false
language: java
jdk: [openjdk8]
env:
  global: [JAVA_OPTS="-Xmx2048M", GRADLE_OPTS="-Xmx2048M"]
jobs:
  include:
  - name: Plug-in registry pull-request
    install: ./gradlew
    script: skip
    deploy:
    - provider: script
      script: bash .travis/registry.sh
      skip_cleanup: true
      true: {tags: true, repo: dita-ot/dita-ot}
notifications:
  slack: {secure: IAA4d9O2Dw1hkpY9cwxJz++VMjkgbV3EuaS09DGFujvHl2eQtpKTloE0/CDF+NZA4tcbH1dNqsGw3ETLmrqA581CLpmiiq3LG02cDMoSXZeOKB/9vo6tvLFg0UMawzo+FomJS/hvCmS5KirrFqZQKE5g6SCC05UBM5nwI5d0vOw=}
branches:
  only: [dita-ot/dita-ot-3819-CONFIGURATION_ON_DEMAND]
