language: android
sudo: false
env:
  global: [TERM=dumb, 'GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"', ANDROID_TARGET=android-19]
before_install: [chmod a+x gradlew, gradle -v, ln -s app.properties-prod assets/app.properties,
  'if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin
    -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86.bin
    -O ndk.bin; fi', chmod a+x ndk.bin, ./ndk.bin  -y | egrep -v ^Extracting, export
    ANDROID_NDK_HOME=`pwd`/android-ndk-r10d, 'export PATH=${PATH}:${ANDROID_NDK_HOME}']
android:
  components: [android-21, platform-tools, tools, build-tools-21.1.2]
script: ['${ANDROID_NDK_HOME}/ndk-build', ./gradlew assembleDebug, 'find . -name ''*.apk''
    -exec ls -l {} \;']
branches:
  only: [opentelecoms-org/lumicall-71-GRADLE_DAEMON]
