sudo: false
language: android
android:
  components: [platform-tools, android-23, build-tools-23.0.3, extra]
jdk: oraclejdk8
notifications: {email: false}
before_install: [sudo apt-get update -qq, 'if [ `uname -m` = x86_64 ]; then sudo apt-get
    install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null;
    fi', mkdir -p ~/.gradle, 'echo "sonatypeRepo=https://oss.sonatype.org/content/repositories/snapshots/"
    > ~/.gradle/gradle.properties', 'echo "sonatypeSnapshotRepo=https://oss.sonatype.org/content/repositories/snapshots/"
    >> ~/.gradle/gradle.properties', echo "sonatypeUsername=xxx" >> ~/.gradle/gradle.properties,
  echo "sonatypePassword=xxx" >> ~/.gradle/gradle.properties]
branches:
  only: [eyeem/chips-android-30-CONFIGURATION_ON_DEMAND]
