language: android
jdk: oraclejdk8
sudo: false
android:
  components: [tools, build-tools-28.0.3, extra-android-support, extra-android-m2repository,
    android-28]
  licenses: [.+, android-sdk-license-.+]
before_install: [yes | sdkmanager "platforms;android-28", yes | sdkmanager "platforms;android-27"]
branches:
  only: [smarek/Simple-Dilbert-61-origin]
