os: linux
dist: trusty
language: java
jdk: [oraclejdk8]
before_cache: [rm -f $HOME/.gradle/caches/modules-2/modules-2.lock]
cache:
  directories: [$HOME/.gradle/caches/, $HOME/.gradle/wrapper/]
deploy:
  provider: releases
  edge: true
  file: build/distributions/gerrit-intellij-plugin-*.zip
  true: {tags: true, condition: '$TRAVIS_TAG =~ ^v[0-9]+.*$'}
after_deploy: [./gradlew publishPlugin]
branches:
  only: [uwolfer/gerrit-intellij-plugin-424-FILE_SYSTEM_WATCHING]
