branches:
  only: [velazcod/Tinfoil-Facebook-133-origin]
language: android
jdk: [oraclejdk8]
env:
  global: [ANDROID_ABI=armeabi-v7a]
  matrix: [ANDROID_TARGET=android-22]
matrix: {fast_finish: true}
android:
  components: [tools, platform-tools, tools, build-tools-25.0.2, android-25, $ANDROID_TARGET,
    extra-android-support, extra-android-m2repository, extra-google-m2repository,
    sys-img-armeabi-v7a-$ANDROID_TARGET]
cache:
  directories: [$HOME/.gradle/caches/, $HOME/.gradle/daemon, $HOME/.gradle/native,
    $HOME/.gradle/wrapper]
before_script: [rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock, rm -fr $HOME/.gradle/caches/*/plugin-resolution/]
install: [TERM=dumb ./gradlew clean assembleDebug -PdisablePreDex]
script: [TERM=dumb ./gradlew check --info]
deploy:
  provider: releases
  file: [app/build/outputs/apk/app-release.apk, app/build/outputs/apk/app-debug.apk]
  skip_cleanup: true
  true: {tags: true, branch: master}
