language: java
install: ['git clone https://github.com/coreos/etcd', pushd etcd && git checkout v0.4.6
    && ./build && popd]
before_script: [etcd/bin/etcd &]
after_script: [pkill -f etcd]
branches:
  only: [diwakergupta/jetcd-21-GRADLE_DAEMON]
