language: android
jdk: [oraclejdk8]
os: linux
dist: trusty
env:
  global: [ANDROID_API_LEVEL=29, ANDROID_BUILD_TOOLS_VERSION=29.0.2, ADB_INSTALL_TIMEOUT=20,
    ANDROID_ABI=armeabi-v7a, ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-19,
    EMULATOR_API_LEVEL=19]
android:
  components: [tools, tools, platform-tools, build-tools-$ANDROID_BUILD_TOOLS_VERSION,
    android-$ANDROID_API_LEVEL, android-$EMULATOR_API_LEVEL, extra-android-support,
    extra-google-m2repository, extra-android-m2repository, extra-google-google_play_services,
    $ANDROID_EMULATOR_IMAGE]
install: [echo yes | sdkmanager "tools", echo yes | sdkmanager "platform-tools", echo
    yes | sdkmanager "build-tools;"$ANDROID_BUILD_TOOLS_VERSION, echo yes | sdkmanager
    "platforms;android-"$ANDROID_API_LEVEL, echo yes | sdkmanager --update]
before_script: [sdkmanager "system-images;android-"$EMULATOR_API_LEVEL";google_apis;armeabi-v7a",
  echo no | avdmanager -v create avd -f -n test -k "system-images;android-"$EMULATOR_API_LEVEL";google_apis;armeabi-v7a",
  $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &, android-wait-for-emulator,
  adb shell settings put global window_animation_scale 0 &, adb shell settings put
    global transition_animation_scale 0 &, adb shell settings put global animator_duration_scale
    0 &, adb shell input keyevent 82 &, adb shell input keyevent 1 &]
script: [./gradlew test, ./gradlew connectedAndroidTest, ./gradlew lint]
branches:
  only: [Countly/countly-sdk-android-134-origin]
