language: android
android:
  components: [build-tools-22.0.1, android-22, extra-android-m2repository]
branches:
  only: [gabrielemariotti/cardslib-573-GRADLE_DAEMON]
notifications: {email: false}
before_install: [export TERM=dumb, ./gradlew -v, uname -a]
script: ./gradlew check
