# This project requires the following ruby gems, buildr addons
gems:
  
repositories:
  remote:
    - http://repo1.maven.org/maven2

artifacts:
  cli: com.vtence.cli:cli:jar:1.1
  simple_common: org.simpleframework:simple-common:jar:6.0.1
  simple_transport: org.simpleframework:simple-transport:jar:6.0.1
  simple_http: org.simpleframework:simple-http:jar:6.0.1
  molecule: com.vtence.molecule:molecule:jar:0.10
  jmustache: com.samskivert:jmustache:jar:1.11
  tape: com.vtence.tape:tape:jar:0.2

  flyway: com.googlecode.flyway:flyway-core:jar:2.0
  mysql: mysql:mysql-connector-java:jar:5.1.21

  # -- test scope
  hamcrest: org.hamcrest:java-hamcrest:jar:2.0.0.0
  cssselectors: se.fishtank:css-selectors:jar:2.0
  hamcrest_dom: com.vtence.hamcrest:hamcrest-dom:jar:2.0.0
  molecule_test: com.vtence.molecule:molecule:jar:tests:0.10
  selenium_firefox_driver: org.seleniumhq.selenium:selenium-firefox-driver:jar:2.53.0
  selenium_ghost_driver: com.codeborne:phantomjsdriver:jar:1.3.0
  mario: com.vtence.mario:mario:jar:0.1
  juniversalchardet: com.googlecode.juniversalchardet:juniversalchardet:jar:1.0.3
  nekohtml: net.sourceforge.nekohtml:nekohtml:jar:1.9.20
  jmock_legacy: org.jmock:jmock-legacy:jar:2.6.0
  jcl_over_slf4j: org.slf4j:jcl-over-slf4j:jar:1.5.6
  slf4j_api: org.slf4j:slf4j-api:jar:1.5.6
  slf4j_silent: org.slf4j:slf4j-nop:jar:1.5.6

junit: 4.11
jmock: 2.6.0

selenium:
  version: 2.53.0
  silent: true
  server:
    url: http://localhost:4444/wd/hub
    browser:
      name: phantomjs
